hello_the_world:
    path: /hello-world
    defaults: { _controller: OCPlatformBundle:Advert:index }

oc_platform_homepage:
    path:     /
    defaults: { _controller: OCPlatformBundle:Default:index }
