oc_platform_homepage:
    path:     /
    defaults: { _controller: OCPlatformBundle:Default:index }

hello_the_world:
    path: /hello-world
    default: { _controller: OCPlatformBundle:Advert:index }
